title: Free Responsive HTML5/CSS3 Template
author:
  name: Peter Finla
metadata:
    description: 'An exclusive HTML5/CSS3 freebie by Peter Finlan, for Codrops.'

# Header customization
header:
  title: I'm Aviral Somani.
  description: I am a Senior in high school in the Dallas/Fort Worth Area. I have a keen interest in <span>learning about the world</span>, <span>engineering</span>, and <span>innovating</span>, through <span>research</span>, <span>invention</span>, <span>programming</span>, and <span>problem-solving</span>. Let's <a class="smoothscroll" href="#about">start scrolling</a> and learn more <a class="smoothscroll" href="#about">about me</a>.

social:
- url: "http://linkedin.com/in/aviral-somani-b62885123"
  icon: linkedin
- url: "@av.ral"
  icon: instagram


# HOW TO CREATE A VALID ID TO USE:
# Go to www.twitter.com and sign in as normal, go to your settings page.
# Go to "Widgets" on the left hand side.
# Create a new widget for what you need eg "user time line" or "search" etc.
# Feel free to check "exclude replies" if you don't want replies in results.
# Now go back to settings page, and then go back to widgets page and
# you should see the widget you just created. Click edit.
# Look at the URL in your web browser, you will see a long number like this:
# 657554810648948736
# Use this as your ID below instead!
